### ISSUE TITLE
Climber atTarget() for retracting pneumatics

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2019-DeepSpace#30]
@pietroglyph The climber should know based on distance sensors when climber is ready to pull the back pneumatics -- ref. to atTarget() --> DRIVING_UNTIL_PLATFORM_FULL_SUPPORT

https://github.com/Spartronics4915/2019-DeepSpace/blob/bbe7e69b79bc0e61e33b64f526ade188a175e608/src/main/java/com/spartronics4915/frc2019/subsystems/Superstructure.java#L184

**Comment by pietroglyph** [comment]
Fixed
