### ISSUE TITLE
If climb reached RETRACTING_REAR_STRUTS turn off all motors

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2019-DeepSpace#31]
@pietroglyph if the climb is completed by pulling the rear pneumatics, we should turn off intake & drive motors. 

https://github.com/Spartronics4915/2019-DeepSpace/blob/bbe7e69b79bc0e61e33b64f526ade188a175e608/src/main/java/com/spartronics4915/frc2019/subsystems/Superstructure.java#L197

**Comment by pietroglyph** [comment]
Fixed by [0530b27c2](https://github.com/Spartronics4915/2019-DeepSpace/commit/0530b27c2c5ad7e3722f0777613874dc5ae27aed).
