### ISSUE TITLE
Missing break??

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2019-DeepSpace#32]
@j-james is there a missing break between case statements? I would think one would like to lower the panel w/o doing a shoot

https://github.com/Spartronics4915/2019-DeepSpace/blob/bbe7e69b79bc0e61e33b64f526ade188a175e608/src/main/java/com/spartronics4915/frc2019/subsystems/CargoChute.java#L146

**Comment by j-james** [comment]
Whoops. I just pushed a fix to my pull request. Thanks!

**Comment by binnur** [comment]
Cool -- you should closed the issue accordingly
