### ISSUE TITLE
What does 'Eject' do?

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2019-DeepSpace#33]
@j-james pls explain the function for ejecting

https://github.com/Spartronics4915/2019-DeepSpace/blob/bbe7e69b79bc0e61e33b64f526ade188a175e608/src/main/java/com/spartronics4915/frc2019/subsystems/CargoChute.java#L132

**Comment by j-james** [comment]
Ejecting overrides any sensors and reverses the ramp, shooting, and intake motors. 
We'd use it if a ball was stuck anywhere within the robot, or if we somehow took in more than one cargo.

**Comment by binnur** [comment]
K -- shouldn't the call to the mRampMotor.set() be reversed? Start w/ negative ramp and stop when timer is done?

**Comment by j-james** [comment]
We don't want to go directly from full speed to full reverse speed, so we have a 1-second stop. Ejecting runs until it's interrupted by another button (usually intake).

**Comment by binnur** [comment]
Got it! Thanks for adding additional comments to the code. Closing!
