### ISSUE TITLE
Pls verify that mCargoChute.atTarget() returns true

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2019-DeepSpace#34]
@pietroglyph @j-james 

Not clear if this code executes as intended in CargoChute.java
```    
   public synchronized boolean atTarget()
  ...
        case BRING_BALL_TO_TOP:
                return mSystemState == SystemState.RAMPING && ballInPosition()
```

https://github.com/Spartronics4915/2019-DeepSpace/blob/bbe7e69b79bc0e61e33b64f526ade188a175e608/src/main/java/com/spartronics4915/frc2019/subsystems/Superstructure.java#L216

**Comment by pietroglyph** [comment]
@j-james Shouldn't your at target be `mSystemState == SystemState.HOLDING && ballInPosition()`?

**Comment by j-james** [comment]
I pushed a change in CargoChute.java.
