### ISSUE TITLE
Missing break??

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2019-DeepSpace#37]
@pietroglyph pls double check intention

https://github.com/Spartronics4915/2019-DeepSpace/blob/bbe7e69b79bc0e61e33b64f526ade188a175e608/src/main/java/com/spartronics4915/frc2019/subsystems/Superstructure.java#L253

**Comment by binnur** [comment]
Also see: https://github.com/Spartronics4915/2019-DeepSpace/blob/bbe7e69b79bc0e61e33b64f526ade188a175e608/src/main/java/com/spartronics4915/frc2019/subsystems/Superstructure.java#L390

**Comment by pietroglyph** [comment]
Oof... Good catch!

**Comment by pietroglyph** [comment]
Fixed by [0530b27c2](https://github.com/Spartronics4915/2019-DeepSpace/commit/0530b27c2c5ad7e3722f0777613874dc5ae27aed).

**Comment by pietroglyph** [comment]
Fixed by [0530b27c2](https://github.com/Spartronics4915/2019-DeepSpace/commit/0530b27c2c5ad7e3722f0777613874dc5ae27aed).
