### ISSUE TITLE
Verify the IR Sensor assignment

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2019-DeepSpace#39]
@AustinTSmith @j-james -- pls ensure this is correct! 
```
 mFrontRightIRSensor = new A41IRSensor(Constants.kFrontLeftIRSensorId);
 mFrontLeftIRSensor = new A21IRSensor(Constants.kFrontRightIRSensorId);
```
https://github.com/Spartronics4915/2019-DeepSpace/blob/cb71895abe5b2d41348902613a6be83130e44a13/src/main/java/com/spartronics4915/frc2019/subsystems/Climber.java#L70

**Comment by AustinTSmith** [comment]
This has been done.
