### ISSUE TITLE
Remove unused sensors from Climber

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2019-DeepSpace#41]
@AustinTSmith @j-james please remove unused sensors from Climber code and sync w/ Peter to ensure wiring is accurate based on latest changes. 

https://github.com/Spartronics4915/2019-DeepSpace/blob/cb71895abe5b2d41348902613a6be83130e44a13/src/main/java/com/spartronics4915/frc2019/subsystems/Climber.java#L47

**Comment by AustinTSmith** [comment]
This has also been done.
