### ISSUE TITLE
Recommend defensive programming for Climber

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2019-DeepSpace#42]
@pietroglyph @AustinTSmith @j-james Currently Climber is relying on the Superstructure for safely transition between states, i.e. atTarget() is the only code that checks on sensor readings. Recommend revising the defaultStateTransfer and state actions to improve robot safety.

**Comment by j-james** [comment]
I talked to Austin about the Climber. Due to the positioning of the HAB (and a lack of buttons to a lesser extent) climbing won't work without the sensors. 

I have added in a stop for the climber, just in case. It just puts the intake in HOLD and keeps the solenoids where they are.
