### ISSUE TITLE
Recommend testing the kTransitionTime

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2019-DeepSpace#43]
@j-james suggest testing this -- seconds add up, so anything we can shave off is a good thing 

https://github.com/Spartronics4915/2019-DeepSpace/blob/7649418a15bb0a80f1561b2da96cf323d9d619cc/src/main/java/com/spartronics4915/frc2019/subsystems/CargoChute.java#L145

**Comment by pietroglyph** [comment]
I agree with @binnur... It's very likely this won't be needed. It's usually not a problem to suddenly reverse motor direction.

**Comment by j-james** [comment]
This was more to make sure the balls wouldn't be worn down or anything when in the ramp (according to Chief Delphi, the cargo are not hard to pop). I commented it out for now because I'd like to test it both ways on the robot.
